services:
  - type: web
    name: notion-gpt-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: DATABASE_ID
        sync: false 